### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by yearofthewhopper** [danielalves/megaman-ios#1]
This code now has 34 errors in the new version of xcode

**Comment by barbosa** [comment]
Hi @yearofthewhopper 

Thanks for reporting. 

This project is just an experiment to play with Swift and SpriteKit and not highly maintained (in general, only during our free time).
Are you able to fix some of them and send us a pull request? If so, we can add you in the contributors list too.

Best regards.

**Comment by yearofthewhopper** [comment]
yes! @barbosa I was able to fix some of them. I'll submit a pull request!

**Comment by danielalves** [comment]
:+1:

**Comment by danielalves** [comment]
@yearofthewhopper I don't know if you are still interested, but @filfrey have submitted a PR fixing all compiler errors. Now megaman is working again, just in time for the [Mighty Number 9](https://www.kickstarter.com/projects/mightyno9/mighty-no-9?ref=card) release! :smile:
